### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by webjay17** [ElanMan/simple-quiz#10]
I believe I have installed correctly.....

However when I run I get
Parse error: syntax error, unexpected '[', expecting ')' in /Applications/XAMPP/xamppfiles/htdocs/public/index.php on line 60

**Comment by ElanMan** [comment]
Hi webjay17,
Which version of php are you using? The code  uses the short array syntax which needs php >= 5.4. I'd forgotten to amend the readme and repo description to reflect that (think it still says min version 5.3.7)

**Comment by webjay17** [comment]
Hi there, 
Thanks for getting back to me appreciate it, sorry my bad. Update PHP version now.
However now am getting

Warning: require(/Applications/XAMPP/xamppfiles/htdocs/simple-quiz-1.9.0/SimpleQuiz/Utils/Base/setup.php): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/simple-quiz-1.9.0/vendor/composer/autoload_real.php on line 54

Fatal error: require(): Failed opening required '/Applications/XAMPP/xamppfiles/htdocs/simple-quiz-1.9.0/SimpleQuiz/Utils/Base/setup.php' (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/simple-quiz-1.9.0/vendor/composer/autoload_real.php on line 54
