### ISSUE TITLE
unable to check the scores of quiz users in admin panel

### ISSUE THREAD

**Issue by Qhadeerz** [ElanMan/simple-quiz#12]
Hi Elan,

I have check in admin panel need to check the users scores and their mistakes like in which question they have attempt a wrong. could you please show the way can i find out the results through an admin panel.

Please do the needful.

Thanks in advance,
Khadeer

**Comment by ElanMan** [comment]
Hi Khadeer,

Thanks for the suggestion. It is definitely something I intend to implement in the future.
At the moment, only the users' total scores and time taken are stored in the database, not the answers they gave for each question.
It should be fairly straight forward to add this but it probably won't be done until Simple Quiz version 2.0.
Thanks for your interest in Simple Quiz.

**Comment by Qhadeerz** [comment]
Ok..thanks for your great response:)
