### ISSUE TITLE
404 Page Not Found

### ISSUE THREAD

**Issue by staverniti** [ElanMan/simple-quiz#14]
Hi - 

I've installed your application on a windows 2008r2 64bit running IIS and PHP 5.6.7 
i've got your application to load the mysql tables and i can see the main page - however if i go to start an exam i immediately get the following
" 404 Page Not Found
The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.

Visit the Home Page"
![capture](https://cloud.githubusercontent.com/assets/11908560/7104713/9001ba7a-e126-11e4-990d-375fd6277dc1.JPG)

i'm not too sure where to go from here, i've check all the folders that they have the correct files as per your readme and they do.

also when i go to try and login with example@gmail.com and password 123456 nothing happens - the fields just reset back to default.

In IIS i edited the web.config file and added the following:
"httpErrors
               remove statusCode="404" subStatusCode="-1" /
               error statusCode="404" prefixLanguageFilePath="" path="/induction/index.php" responseMode="ExecuteURL" /
           /httpErrors" -
so it would pass the 404 errors back to index.php ( this resolved an issue i was initially having when i first went to load your application )

i'm at a loss here, can you please help?

thank you

**Comment by ElanMan** [comment]
Hi,
I'm not too familiar with running IIS.
The simple quiz application depends on an apache .htaccess file to rewrite the URLs.
I don't know what the equivalent is on IIS but it sounds like that might be your problem...
Have a look at ISAPI_Rewrite (I think) for IIS.

**Comment by staverniti** [comment]
Thanks ElanMan!

i downloaded URL Rewrite for IIS and imported your .htaccess file rule in and bingo we are up and running now!

there was a bit of initial mucking around getting everything working with PHP, IIS etc but now it seems to be running fine.

Thankyou for your help
