### ISSUE TITLE
Question storage needs to be increase

### ISSUE THREAD

**Issue by Qhadeerz** [ElanMan/simple-quiz#17]
Hi Elan,

I am unable to save the lengthy questions using simple quiz application, could you please navigate/show the way how to increase the data type/ storage of questions. i need to save lengthy questions also please do the needful.

Thanks in advance.

Khadeer

**Comment by razuro** [comment]
Can you show your question example? If not, go to your questions table, change the datatype for text, from VARCHAR to TEXT/LONGTEXT.

**Comment by Qhadeerz** [comment]
Hi Razuro,

I have done. Thanks alot.

Appreciate for your support.
