### ISSUE TITLE
Mail error when registering

### ISSUE THREAD

**Issue by jaredb13** [ElanMan/simple-quiz#23]
I get this error when I register a new user. The user gets registered but its disconcerting for them, and email isn't working obviously.

---

Details
Type: Swift_RfcComplianceException
Message: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
File: /home/tautline/public_html/simple-quiz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php
Line: 348
Trace
#0 /home/tautline/public_html/simple-quiz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('')
#1 /home/tautline/public_html/simple-quiz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /home/tautline/public_html/simple-quiz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /home/tautline/public_html/simple-quiz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMimeEntity.php(602): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /home/tautline/public_html/simple-quiz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(213): Swift_Mime_SimpleMimeEntity->_setHeaderFieldModel('From', Array)
#5 /home/tautline/public_html/simple-quiz/SimpleQuiz/Utils/Base/Mailer.php(25): Swift_Mime_SimpleMessage->setFrom(Array)
#6 /home/tautline/public_html/simple-quiz/routes/public.php(138): SimpleQuiz\Utils\Base\Mailer->__construct()
#7 [internal function]: {closure}()
#8 /home/tautline/public_html/simple-quiz/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#9 /home/tautline/public_html/simple-quiz/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#10 /home/tautline/public_html/simple-quiz/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#11 /home/tautline/public_html/simple-quiz/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#12 /home/tautline/public_html/simple-quiz/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#13 /home/tautline/public_html/simple-quiz/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#14 /home/tautline/public_html/simple-quiz/public/index.php(56): Slim\Slim->run()
#15 {main}

**Comment by coolashish** [comment]
In Config.php, for the appEmail field, enter your email address. Currently this field is blank as indicated by '[]'
