### ISSUE TITLE
Admin settings link broken

### ISSUE THREAD

**Issue by jamezyc123** [ElanMan/simple-quiz#30]
When logged in as an Admin both the settings and change password links in the drop down redirect to admin/config/ and admin/edit respectively, which are not directories in this package. Perhaps I am doing something wrong?

**Comment by ElanMan** [comment]
Hi, the links in the dropdown have a class of disabled, so they should be unclickable (see screenshot).
![simple_quiz_admin_-_2017-04-04_20 39 50](https://cloud.githubusercontent.com/assets/1465363/24675529/5fe3019c-1977-11e7-8f29-8e0252749f66.png)

Unfortunately, those features haven't been implemented.
